### ISSUE TITLE
Initial Release Roadmap

### ISSUE THREAD

**Issue by MeatCow** [andy2great/NX-Generatorz#29]
This issue outlines the features the team deems necessary before creating an initial release.

1. Once all items are complete, we can consider creating a 14.x branch that follows nrwl's 14.x version and move the release stuff to main. This is still up in the air in case nrwl changes major versions before we release, or in case we want to support more than just 14.x.

## Required features

- [x] Have a rename generator. People don't find the move generator intuitive (#10)
- [x] Make shared option in UI generator optional (#13)
- [x] Add initial tests for generators. Future generators, and features must be tested (#21)

## Would be nice features
- [ ] Create a remove generator with project selection via dropdown (#18)
- [ ] Create a simplified generator for Storybook (#16)
- [x] Implement a CD. Not necessarily a requirement, but it would be nice to be part of the initial release. (#23)
- [x] Implement an executor that bumps major/minor/patch versions (#24)
- [x] CI - Cache npm install(#26)

**Comment by MeatCow** [comment]
@armenbalian @andy2great @My-man-Spood
How would you guys feel about a release deadline for this project on 👀 26/01 👀 ?

I feel like although we don't have all the features in the list, it's still in a releasable state 🚀

**Comment by andy2great** [comment]
YESSIR MILLER :rocket:
